name: Run Behave tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Main_Controller
        pip install -r requirements.txt
        
    - name: Decrypt and use sensitive file
      run: |
        cd Main_Controller/logic
        openssl aes-256-cbc -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }} -in mqtt_package/mqtt_resources.yaml.enc -out mqtt_package/mqtt_resources.yaml -d
        openssl aes-256-cbc -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }} -in database_package/influx_config.yaml.enc -out database_package/influx_config.yaml -d
        ls -R
        cat mqtt_package/mqtt_resources.yaml
        cat database_package/influx_config.yaml

    - name: Run Behave tests
      run: |
        cd Main_Controller
        behave
