name: Run Behave tests

on:
  push:
    branches:
      - main

jobs:
  test:
    
    runs-on: ubuntu-latest

    env:
      INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
      INFLUX_URL: ${{ secrets.INFLUX_URL }}
      MQTT_BROKER_ADDRESS: ${{ secrets.MQTT_BROKER_ADDRESS }}
      MQTT_BROKER_PORT: ${{ secrets.MQTT_BROKER_PORT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Main_Controller
        pip install -r requirements.txt

    - name: Run Behave tests
      run: |
        cd Main_Controller
        behave
